# Generated by Django 5.2.11 on 2026-02-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('supporter', 'Supporter')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('chassis', 'Chassis'), ('powertrain', 'Powertrain'), ('control', 'Control'), ('safety', 'Safety'), ('storage', 'Storage'), ('dynamics', 'Dynamics'), ('electrical', 'Electrical'), ('other', 'Other')], max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🔧', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('specs', models.JSONField(blank=True, default=list, help_text='JSON array of spec strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.season')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='api.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('engine_type', models.CharField(choices=[('ICE', 'Internal Combustion Engine'), ('EV', 'Electric Vehicle'), ('HYBRID', 'Hybrid')], default='ICE', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active / Current Build'), ('completed', 'Completed'), ('legacy', 'Legacy')], default='completed', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='JSON object of key-value spec pairs')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='JSON array of highlight strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='api.season')),
            ],
            options={
                'ordering': ['-season__number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('lead', 'Team Lead'), ('mechanical', 'Mechanical Engineer'), ('powertrain', 'Powertrain Engineer'), ('dynamics', 'Vehicle Dynamics'), ('electronics', 'Electronics & Controls'), ('business', 'Business & Marketing'), ('design', 'Design & Media'), ('member', 'Member')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Custom title (e.g., Chassis Lead)', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Student year', null=True)),
                ('is_alumni', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.season')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
